name: stable-audio-open-modal
channels:
  - defaults
  - roebel
dependencies:
  - python=3.10
  - pip
  - pysndfile
  - pip:
    - torch
    - torchaudio
    - pysndfile
    - stable-audio-tools
    - fastapi[standard]
    - pydantic
    - modal
